# Generated by Django 5.0.4 on 2025-04-06 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = []
